#!/bin/bash

deploy="$HOME/deploy"

for dir in $(find "$deploy" -maxdepth 1 -mindepth 1 -type l); do
    (cd "$dir" && [ -d ".git" ] && { git diff --quiet || { echo "$(basename $dir)" && git diff --stat; } ; })
done
