#!/bin/bash
outdir="${SCREENSHOTS:-/tmp}"
find "$outdir" -maxdepth 1 -type f -regextype grep -iregex '.*\.\(png\|jpg\|jpeg\|gif\)$' -printf "%T+\t%p\n" | sort | grep -vP 'hc.png|hc_prev' | tail -n1 | awk -F"\t" '{print $2}'
