#!/bin/bash
miscdir="$(dirname -- "$(readlink -f -- "$0")")"


file="$1"


cp "$file" "$miscdir"
newpath="$miscdir/$(basename "$file")"


if [ -x "$file" ]; then
    ln -sf "$newpath" "$HOME/bin/"
fi


(
    set -e
    cd "$miscdir";
    git stash
    git add "$newpath"
    git commit -m "Add $(basename $file)"
    git stash pop
)
